---
# docker compose up -d
# docker compose up --build
# docker compose down
# docker compose down -v

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    command: /bin/bash /entrypoint.sh
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=SomeStrongPwd123
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -U sa -P SomeStrongPwd123 -Q 'SELECT 1'"]
      start_period: 20s
    volumes:
      - mssqldata:/var/opt/mssql
      - ./db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./db/mssql/docker-db-init.sh:/db-init.sh
      - ./db/mssql/mssql-cars.sql:/db-init.sql

  netcore-boilerplate:
    container_name: netcore-boilerplate
    build:
      context: .
    ports:
      - 5000:8080
    environment:
      FeatureManagement__DockerCompose: true
    depends_on:
      - mssql

  nextjs-admin:
    container_name: nextjs-admin
    build:
      context: ./admin-panel
    ports:
      - 3000:3000
    volumes:
      - ./admin-panel:/app
    environment:
      - NODE_ENV=production

volumes:
  mssqldata:
